baseurl: /
title: Language Gates
author: Teodor PetriÄ
canonifyurls: yes
paginate: 3
theme: aether
params:
  brand: aether
  description: aether Hugo theme for blogs
  headshotimg: img/faceshot.gif
markup:
  highlight:
    style: igor
